
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.loginInfo
{
public sealed partial class LoginInfo : Luban.BeanBase
{
    public LoginInfo(ByteBuf _buf) 
    {
        Username = _buf.ReadString();
        Password = _buf.ReadInt();
    }

    public static LoginInfo DeserializeLoginInfo(ByteBuf _buf)
    {
        return new loginInfo.LoginInfo(_buf);
    }

    /// <summary>
    /// 用户名
    /// </summary>
    public readonly string Username;
    /// <summary>
    /// 密码
    /// </summary>
    public readonly int Password;
   
    public const int __ID__ = 255349280;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "username:" + Username + ","
        + "password:" + Password + ","
        + "}";
    }
}

}

