
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.loginInfo
{
public partial class TbInfo
{
    private readonly System.Collections.Generic.Dictionary<string, loginInfo.LoginInfo> _dataMap;
    private readonly System.Collections.Generic.List<loginInfo.LoginInfo> _dataList;
    
    public TbInfo(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, loginInfo.LoginInfo>();
        _dataList = new System.Collections.Generic.List<loginInfo.LoginInfo>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            loginInfo.LoginInfo _v;
            _v = global::GameConfig.loginInfo.LoginInfo.DeserializeLoginInfo(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Username, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, loginInfo.LoginInfo> DataMap => _dataMap;
    public System.Collections.Generic.List<loginInfo.LoginInfo> DataList => _dataList;

    public loginInfo.LoginInfo GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public loginInfo.LoginInfo Get(string key) => _dataMap[key];
    public loginInfo.LoginInfo this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

