
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.ybtest
{
public partial class Tb
{
    private readonly System.Collections.Generic.Dictionary<int, ybtest.Ybtest> _dataMap;
    private readonly System.Collections.Generic.List<ybtest.Ybtest> _dataList;
    
    public Tb(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ybtest.Ybtest>();
        _dataList = new System.Collections.Generic.List<ybtest.Ybtest>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            ybtest.Ybtest _v;
            _v = global::GameConfig.ybtest.Ybtest.DeserializeYbtest(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ybtest.Ybtest> DataMap => _dataMap;
    public System.Collections.Generic.List<ybtest.Ybtest> DataList => _dataList;

    public ybtest.Ybtest GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ybtest.Ybtest Get(int key) => _dataMap[key];
    public ybtest.Ybtest this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

